# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
# 10.times do
#   User.create!(
#     email: Faker::Internet.email, 
#     password: "password", 
#     password_confirmation: "password"
#   )

  Diagnosis.create(slug: "Abdominal aortic aneurysm", description: "")
  Diagnosis.create(slug: "Acne", description: "")
  Diagnosis.create(slug: "Acute cholecystitis", description: "")
  Diagnosis.create(slug: "Acute lymphoblastic leukaemia", description: "")
  Diagnosis.create(slug: "Acute lymphoblastic leukaemia: Children", description: "")
  Diagnosis.create(slug: "Acute lymphoblastic leukaemia: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Acute myeloid leukaemia", description: "")
  Diagnosis.create(slug: "Acute myeloid leukaemia: Children", description: "")
  Diagnosis.create(slug: "Acute myeloid leukaemia: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Acute pancreatitis", description: "")
  Diagnosis.create(slug: "Adenomyosis", description: "")
  Diagnosis.create(slug: "Addison’s disease", description: "")
  Diagnosis.create(slug: "Alcohol-related liver disease", description: "")
  Diagnosis.create(slug: "Allergic rhinitis", description: "")
  Diagnosis.create(slug: "Allergies", description: "")
  Diagnosis.create(slug: "Alzheimer’s disease", description: "")
  Diagnosis.create(slug: "Anaphylaxis", description: "")
  Diagnosis.create(slug: "Angina", description: "")
  Diagnosis.create(slug: "Angioedema", description: "")
  Diagnosis.create(slug: "Ankylosing spondylitis", description: "")
  Diagnosis.create(slug: "Anorexia nervosa", description: "")
  Diagnosis.create(slug: "Anxiety", description: "")
  Diagnosis.create(slug: "Anxiety disorders in children", description: "")
  Diagnosis.create(slug: "Appendicitis", description: "")
  Diagnosis.create(slug: "Arterial thrombosis", description: "")
  Diagnosis.create(slug: "Arthritis", description: "")
  Diagnosis.create(slug: "Asbestosis", description: "")
  Diagnosis.create(slug: "Asthma", description: "")
  Diagnosis.create(slug: "Atopic eczema", description: "")
  Diagnosis.create(slug: "Atrial fibrillation", description: "")
  Diagnosis.create(slug: "Attention deficit hyperactivity disorder (ADHD)", description: "")
  Diagnosis.create(slug: "Autistic spectrum disorder (ASD)", description: "")
  Diagnosis.create(slug: "Bacterial vaginosis", description: "")
  Diagnosis.create(slug: "Benign prostate enlargement", description: "")
  Diagnosis.create(slug: "Bile duct cancer (cholangiocarcinoma)", description: "")
  Diagnosis.create(slug: "Binge eating", description: "")
  Diagnosis.create(slug: "Bipolar disorder", description: "")
  Diagnosis.create(slug: "Bladder cancer", description: "")
  Diagnosis.create(slug: "Blood poisoning (sepsis)", description: "")
  Diagnosis.create(slug: "Bone cancer", description: "")
  Diagnosis.create(slug: "Bone cancer: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Bowel cancer", description: "")
  Diagnosis.create(slug: "Bowel incontinence", description: "")
  Diagnosis.create(slug: "Bowel polyps", description: "")
  Diagnosis.create(slug: "Brain stem death", description: "")
  Diagnosis.create(slug: "Brain tumours", description: "")
  Diagnosis.create(slug: "Brain tumours: Children", description: "")
  Diagnosis.create(slug: "Brain tumours: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Breast cancer (female)", description: "")
  Diagnosis.create(slug: "Breast cancer (male)", description: "")
  Diagnosis.create(slug: "Bronchiectasis", description: "")
  Diagnosis.create(slug: "Bronchitis", description: "")
  Diagnosis.create(slug: "Bulimia", description: "")
  Diagnosis.create(slug: "Bunion", description: "")
  Diagnosis.create(slug: "Carcinoid syndrome and carcinoid tumours", description: "")
  Diagnosis.create(slug: "Catarrh", description: "")
  Diagnosis.create(slug: "Cellulitis", description: "")
  Diagnosis.create(slug: "Cerebral palsy", description: "")
  Diagnosis.create(slug: "Cervical cancer", description: "")
  Diagnosis.create(slug: "Chest infection", description: "")
  Diagnosis.create(slug: "Chest pain", description: "")
  Diagnosis.create(slug: "Chickenpox", description: "")
  Diagnosis.create(slug: "Chilblains", description: "")
  Diagnosis.create(slug: "Chlamydia", description: "")
  Diagnosis.create(slug: "Chronic fatigue syndrome", description: "")
  Diagnosis.create(slug: "Chronic kidney disease", description: "")
  Diagnosis.create(slug: "Chronic lymphocytic leukaemia", description: "")
  Diagnosis.create(slug: "Chronic myeloid leukaemia", description: "")
  Diagnosis.create(slug: "Chronic obstructive pulmonary disease", description: "")
  Diagnosis.create(slug: "Chronic pain", description: "")
  Diagnosis.create(slug: "Chronic pancreatitis", description: "")
  Diagnosis.create(slug: "Cirrhosis", description: "")
  Diagnosis.create(slug: "Clostridium difficile", description: "")
  Diagnosis.create(slug: "Coeliac disease", description: "")
  Diagnosis.create(slug: "Cold sore", description: "")
  Diagnosis.create(slug: "Coma", description: "")
  Diagnosis.create(slug: "Common cold", description: "")
  Diagnosis.create(slug: "Common heart conditions", description: "")
  Diagnosis.create(slug: "Congenital heart disease", description: "")
  Diagnosis.create(slug: "Conjunctivitis", description: "")
  Diagnosis.create(slug: "Constipation", description: "")
  Diagnosis.create(slug: "Coronavirus (COVID-19)", description: "")
  Diagnosis.create(slug: "Cough", description: "")
  Diagnosis.create(slug: "Crohn’s disease", description: "")
  Diagnosis.create(slug: "Croup", description: "")
  Diagnosis.create(slug: "Cystic fibrosis", description: "")
  Diagnosis.create(slug: "Cystitis", description: "")
  Diagnosis.create(slug: "Deafblindness", description: "")
  Diagnosis.create(slug: "Deep vein thrombosis", description: "")
  Diagnosis.create(slug: "Dehydration", description: "")
  Diagnosis.create(slug: "Dementia", description: "")
  Diagnosis.create(slug: "Dementia with Lewy bodies", description: "")
  Diagnosis.create(slug: "Dental abscess", description: "")
  Diagnosis.create(slug: "Depression", description: "")
  Diagnosis.create(slug: "Dermatitis herpetiformis", description: "")
  Diagnosis.create(slug: "Diabetes", description: "")
  Diagnosis.create(slug: "Diarrhoea", description: "")
  Diagnosis.create(slug: "Discoid eczema", description: "")
  Diagnosis.create(slug: "Diverticular disease and diverticulitis", description: "")
  Diagnosis.create(slug: "Dizziness (Lightheadedness)", description: "")
  Diagnosis.create(slug: "Down’s syndrome", description: "")
  Diagnosis.create(slug: "Dry mouth", description: "")
  Diagnosis.create(slug: "Dysphagia (swallowing problems)", description: "")
  Diagnosis.create(slug: "Dystonia", description: "")
  Diagnosis.create(slug: "Ebola virus disease", description: "")
  Diagnosis.create(slug: "Ectopic pregnancy", description: "")
  Diagnosis.create(slug: "Edwards’ syndrome", description: "")
  Diagnosis.create(slug: "Endometriosis", description: "")
  Diagnosis.create(slug: "Epilepsy", description: "")
  Diagnosis.create(slug: "Erectile dysfunction (impotence)", description: "")
  Diagnosis.create(slug: "Escherichia coli (E. coli) O157", description: "")
  Diagnosis.create(slug: "Ewing sarcoma", description: "")
  Diagnosis.create(slug: "Ewing sarcoma: Children", description: "")
  Diagnosis.create(slug: "Eye cancer", description: "")
  Diagnosis.create(slug: "Febrile seizures", description: "")
  Diagnosis.create(slug: "Feeling of something in your throat (Globus)", description: "")
  Diagnosis.create(slug: "Fever in adults", description: "")
  Diagnosis.create(slug: "Fever in children", description: "")
  Diagnosis.create(slug: "Fibroids", description: "")
  Diagnosis.create(slug: "Fibromyalgia", description: "")
  Diagnosis.create(slug: "Farting", description: "")
  Diagnosis.create(slug: "Flu", description: "")
  Diagnosis.create(slug: "Fetal alcohol syndrome", description: "")
  Diagnosis.create(slug: "Food poisoning", description: "")
  Diagnosis.create(slug: "Functional neurological disorder (FND)", description: "")
  Diagnosis.create(slug: "Fungal nail infection", description: "")
  Diagnosis.create(slug: "Gallbladder cancer", description: "")
  Diagnosis.create(slug: "Gallstones", description: "")
  Diagnosis.create(slug: "Ganglion cyst", description: "")
  Diagnosis.create(slug: "Gastroenteritis", description: "")
  Diagnosis.create(slug: "Gastro-oesophageal reflux disease (GORD)", description: "")
  Diagnosis.create(slug: "Genital herpes", description: "")
  Diagnosis.create(slug: "Genital symptoms", description: "")
  Diagnosis.create(slug: "Genital warts", description: "")
  Diagnosis.create(slug: "Germ cell tumours", description: "")
  Diagnosis.create(slug: "Glandular fever", description: "")
  Diagnosis.create(slug: "Gonorrhoea", description: "")
  Diagnosis.create(slug: "Gout", description: "")
  Diagnosis.create(slug: "Gum disease", description: "")
  Diagnosis.create(slug: "Haemorrhoids (piles)", description: "")
  Diagnosis.create(slug: "Hand, foot and mouth disease", description: "")
  Diagnosis.create(slug: "Hay fever", description: "")
  Diagnosis.create(slug: "Head and neck cancer", description: "")
  Diagnosis.create(slug: "Head lice and nits", description: "")
  Diagnosis.create(slug: "Headaches", description: "")
  Diagnosis.create(slug: "Hearing loss", description: "")
  Diagnosis.create(slug: "Heart attack", description: "")
  Diagnosis.create(slug: "Heart failure", description: "")
  Diagnosis.create(slug: "Hepatitis A", description: "")
  Diagnosis.create(slug: "Hepatitis B", description: "")
  Diagnosis.create(slug: "Hepatitis C", description: "")
  Diagnosis.create(slug: "Hiatus hernia", description: "")
  Diagnosis.create(slug: "High cholesterol", description: "")
  Diagnosis.create(slug: "HIV", description: "")
  Diagnosis.create(slug: "Hodgkin lymphoma", description: "")
  Diagnosis.create(slug: "Hodgkin lymphoma: Children", description: "")
  Diagnosis.create(slug: "Hodgkin lymphoma: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Huntington’s disease", description: "")
  Diagnosis.create(slug: "Hyperglycaemia (high blood sugar)", description: "")
  Diagnosis.create(slug: "Hyperhidrosis", description: "")
  Diagnosis.create(slug: "Hypoglycaemia (low blood sugar)", description: "")
  Diagnosis.create(slug: "Idiopathic pulmonary fibrosis", description: "")
  Diagnosis.create(slug: "Impetigo", description: "")
  Diagnosis.create(slug: "Indigestion", description: "")
  Diagnosis.create(slug: "Ingrown toenail", description: "")
  Diagnosis.create(slug: "Inherited heart conditions", description: "")
  Diagnosis.create(slug: "Insomnia", description: "")
  Diagnosis.create(slug: "Iron deficiency anaemia", description: "")
  Diagnosis.create(slug: "Irritable bowel syndrome (IBS)", description: "")
  Diagnosis.create(slug: "Itching", description: "")
  Diagnosis.create(slug: "Itchy bottom", description: "")
  Diagnosis.create(slug: "Kaposi’s sarcoma", description: "")
  Diagnosis.create(slug: "Kidney cancer", description: "")
  Diagnosis.create(slug: "Kidney infection", description: "")
  Diagnosis.create(slug: "Kidney stones", description: "")
  Diagnosis.create(slug: "Labyrinthitis", description: "")
  Diagnosis.create(slug: "Lactose intolerance", description: "")
  Diagnosis.create(slug: "Laryngeal (larynx) cancer", description: "")
  Diagnosis.create(slug: "Laryngitis", description: "")
  Diagnosis.create(slug: "Lichen planus", description: "")
  Diagnosis.create(slug: "Lipoedema", description: "")
  Diagnosis.create(slug: "Liver cancer", description: "")
  Diagnosis.create(slug: "Liver disease", description: "")
  Diagnosis.create(slug: "Liver tumours", description: "")
  Diagnosis.create(slug: "Loss of libido", description: "")
  Diagnosis.create(slug: "Lung cancer", description: "")
  Diagnosis.create(slug: "Lupus", description: "")
  Diagnosis.create(slug: "Lyme disease", description: "")
  Diagnosis.create(slug: "Lymphoedema", description: "")
  Diagnosis.create(slug: "Lymphogranuloma venereum (LGV)", description: "")
  Diagnosis.create(slug: "Malaria", description: "")
  Diagnosis.create(slug: "Malignant brain tumour (cancerous)", description: "")
  Diagnosis.create(slug: "Malnutrition", description: "")
  Diagnosis.create(slug: "Measles", description: "")
  Diagnosis.create(slug: "Meningitis", description: "")
  Diagnosis.create(slug: "Menopause", description: "")
  Diagnosis.create(slug: "Mesothelioma", description: "")
  Diagnosis.create(slug: "Middle ear infection (otitis media)", description: "")
  Diagnosis.create(slug: "Migraine", description: "")
  Diagnosis.create(slug: "Miscarriage", description: "")
  Diagnosis.create(slug: "Motor neurone disease (MND)", description: "")
  Diagnosis.create(slug: "Mouth cancer", description: "")
  Diagnosis.create(slug: "Mouth ulcer", description: "")
  Diagnosis.create(slug: "Multiple myeloma", description: "")
  Diagnosis.create(slug: "Multiple sclerosis (MS)", description: "")
  Diagnosis.create(slug: "Mumps", description: "")
  Diagnosis.create(slug: "Meniere’s disease", description: "")
  Diagnosis.create(slug: "Myasthenia gravis", description: "")
  Diagnosis.create(slug: "Nasal and sinus cancer", description: "")
  Diagnosis.create(slug: "Nasopharyngeal cancer", description: "")
  Diagnosis.create(slug: "Neuroblastoma: Children", description: "")
  Diagnosis.create(slug: "Neuroendocrine tumours", description: "")
  Diagnosis.create(slug: "Non-alcoholic fatty liver disease (NAFLD)", description: "")
  Diagnosis.create(slug: "Non-Hodgkin lymphoma", description: "")
  Diagnosis.create(slug: "Non-Hodgkin lymphoma: Children", description: "")
  Diagnosis.create(slug: "Norovirus", description: "")
  Diagnosis.create(slug: "Nosebleed", description: "")
  Diagnosis.create(slug: "Obesity", description: "")
  Diagnosis.create(slug: "Obsessive compulsive disorder (OCD)", description: "")
  Diagnosis.create(slug: "Obstructive sleep apnoea", description: "")
  Diagnosis.create(slug: "Oesophageal cancer", description: "")
  Diagnosis.create(slug: "Oral thrush in adults", description: "")
  Diagnosis.create(slug: "Osteoporosis", description: "")
  Diagnosis.create(slug: "Osteosarcoma", description: "")
  Diagnosis.create(slug: "Outer ear infection (otitis externa)", description: "")
  Diagnosis.create(slug: "Ovarian cancer", description: "")
  Diagnosis.create(slug: "Ovarian cancer: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Ovarian cyst", description: "")
  Diagnosis.create(slug: "Overactive thyroid", description: "")
  Diagnosis.create(slug: "Paget’s disease of the nipple", description: "")
  Diagnosis.create(slug: "Pancreatic cancer", description: "")
  Diagnosis.create(slug: "Panic disorder", description: "")
  Diagnosis.create(slug: "Parkinson’s disease", description: "")
  Diagnosis.create(slug: "Patau’s syndrome", description: "")
  Diagnosis.create(slug: "Pelvic inflammatory disease", description: "")
  Diagnosis.create(slug: "Pelvic organ prolapse", description: "")
  Diagnosis.create(slug: "Penile cancer", description: "")
  Diagnosis.create(slug: "Peripheral neuropathy", description: "")
  Diagnosis.create(slug: "Personality disorder", description: "")
  Diagnosis.create(slug: "Pleurisy", description: "")
  Diagnosis.create(slug: "Pneumonia", description: "")
  Diagnosis.create(slug: "Polycystic ovary syndrome (PCOS)", description: "")
  Diagnosis.create(slug: "Polymyalgia rheumatica", description: "")
  Diagnosis.create(slug: "Post-polio syndrome", description: "")
  Diagnosis.create(slug: "Post-traumatic stress disorder (PTSD)", description: "")
  Diagnosis.create(slug: "Postnatal depression", description: "")
  Diagnosis.create(slug: "Pregnancy and baby", description: "")
  Diagnosis.create(slug: "Pressure ulcers", description: "")
  Diagnosis.create(slug: "Prostate cancer", description: "")
  Diagnosis.create(slug: "Psoriasis", description: "")
  Diagnosis.create(slug: "Psoriatic arthritis", description: "")
  Diagnosis.create(slug: "Psychosis", description: "")
  Diagnosis.create(slug: "Pubic lice", description: "")
  Diagnosis.create(slug: "Rare tumours", description: "")
  Diagnosis.create(slug: "Raynaud’s phenomenon", description: "")
  Diagnosis.create(slug: "Reactive arthritis", description: "")
  Diagnosis.create(slug: "Restless legs syndrome", description: "")
  Diagnosis.create(slug: "Retinoblastoma: Children", description: "")
  Diagnosis.create(slug: "Rhabdomyosarcoma", description: "")
  Diagnosis.create(slug: "Rheumatoid arthritis", description: "")
  Diagnosis.create(slug: "Ringworm and other fungal infections", description: "")
  Diagnosis.create(slug: "Rosacea", description: "")
  Diagnosis.create(slug: "Scabies", description: "")
  Diagnosis.create(slug: "Scarlet fever", description: "")
  Diagnosis.create(slug: "Schizophrenia", description: "")
  Diagnosis.create(slug: "Scoliosis", description: "")
  Diagnosis.create(slug: "Septic shock", description: "")
  Diagnosis.create(slug: "Shingles", description: "")
  Diagnosis.create(slug: "Shortness of breath", description: "")
  Diagnosis.create(slug: "Sickle cell disease", description: "")
  Diagnosis.create(slug: "Sinusitis", description: "")
  Diagnosis.create(slug: "Sjogren’s syndrome", description: "")
  Diagnosis.create(slug: "Skin cancer (melanoma)", description: "")
  Diagnosis.create(slug: "Skin cancer (non-melanoma)", description: "")
  Diagnosis.create(slug: "Skin rashes in children", description: "")
  Diagnosis.create(slug: "Slapped cheek syndrome", description: "")
  Diagnosis.create(slug: "Soft tissue sarcomas", description: "")
  Diagnosis.create(slug: "Soft tissue sarcomas: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Spleen problems and spleen removal", description: "")
  Diagnosis.create(slug: "Stillbirth", description: "")
  Diagnosis.create(slug: "Stomach ache and abdominal pain", description: "")
  Diagnosis.create(slug: "Stomach cancer", description: "")
  Diagnosis.create(slug: "Stomach ulcer", description: "")
  Diagnosis.create(slug: "Streptococcus A (strep A)", description: "")
  Diagnosis.create(slug: "Stress, anxiety and low mood", description: "")
  Diagnosis.create(slug: "Sudden infant death syndrome (SIDS)", description: "")
  Diagnosis.create(slug: "Suicide", description: "")
  Diagnosis.create(slug: "Sunburn", description: "")
  Diagnosis.create(slug: "Supraventricular tachycardia", description: "")
  Diagnosis.create(slug: "Syphilis", description: "")
  Diagnosis.create(slug: "Testicular cancer", description: "")
  Diagnosis.create(slug: "Testicular cancer: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Testicular lumps and swellings", description: "")
  Diagnosis.create(slug: "Threadworms", description: "")
  Diagnosis.create(slug: "Thrush", description: "")
  Diagnosis.create(slug: "Thyroid cancer", description: "")
  Diagnosis.create(slug: "Thyroid cancer: Teenagers and young adults", description: "")
  Diagnosis.create(slug: "Tinnitus", description: "")
  Diagnosis.create(slug: "Tonsillitis", description: "")
  Diagnosis.create(slug: "Toothache", description: "")
  Diagnosis.create(slug: "Transient ischaemic attack (TIA)", description: "")
  Diagnosis.create(slug: "Trigeminal neuralgia", description: "")
  Diagnosis.create(slug: "Tuberculosis (TB)", description: "")
  Diagnosis.create(slug: "Type 1 diabetes", description: "")
  Diagnosis.create(slug: "Type 2 diabetes", description: "")
  Diagnosis.create(slug: "Trichomonas infection", description: "")
  Diagnosis.create(slug: "Transverse myelitis", description: "")
  Diagnosis.create(slug: "Ulcerative colitis", description: "")
  Diagnosis.create(slug: "Underactive thyroid", description: "")
  Diagnosis.create(slug: "Urinary incontinence", description: "")
  Diagnosis.create(slug: "Urinary tract infection (UTI)", description: "")
  Diagnosis.create(slug: "Urinary tract infection (UTI) in children", description: "")
  Diagnosis.create(slug: "Urticaria (hives)", description: "")
  Diagnosis.create(slug: "Vaginal cancer", description: "")
  Diagnosis.create(slug: "Vaginal discharge", description: "")
  Diagnosis.create(slug: "Varicose eczema", description: "")
  Diagnosis.create(slug: "Venous leg ulcer", description: "")
  Diagnosis.create(slug: "Vertigo", description: "")
  Diagnosis.create(slug: "Vitamin B12 or folate deficiency anaemia", description: "")
  Diagnosis.create(slug: "Vulval cancer", description: "")
  Diagnosis.create(slug: "Warts and verrucas", description: "")
  Diagnosis.create(slug: "Whooping cough", description: "")
  Diagnosis.create(slug: "Wilms’ tumour", description: "")
  Diagnosis.create(slug: "Womb (uterus) cancer", description: "")
  Diagnosis.create(slug: "Yellow fever", description: "")
